### PR TITLE
Refactored the code to be shorter and cleaner

### PR DESCRIPTION
**Pull request by GabrielRavier**
Also remove some redundant spaces

### CODE REVIEW

**Comment by norech** [comment]
The redundancy of the tests function is voluntary actually. It is made specifically to ease the contribution for people who aren't very comfortable with shell scripting. So one of the points is to reduce the "syntaxic" complexity of the top part of the file, even if it make it more redundant.

**Comment by GabrielRavier** [comment]
I can see how that makes sense for parts of the code, but I don't think random empty lines and the way signals are handled (which is very highly redundant) contribute to making it all "simpler".

**Comment by norech** [comment]
I may agree for the signals part.

**Comment by norech** [comment]
But if we could avoid extensive use of "bashisms" in the top part, that would be nice though.

**Comment by GabrielRavier** [comment]
What parts of this PR use a bashism ? By "bashism", do you just mean "complicated syntax" ? I'm pretty sure this is stuff I could do with a stricly POSIX `/bin/sh`...

**Comment by GabrielRavier** [comment]
Also, I've reverted everything except for the signal code simplification and some minor whitespace removal.

**Comment by norech** [comment]
> What parts of this PR use a bashism ? By "bashism", do you just mean "complicated syntax" ? I'm pretty sure this is stuff I could do with a stricly POSIX `/bin/sh`...

Yeah I just meant "complicated syntax".

**Pull request merged**
